### ISSUE TITLE
sounddevice error

### ISSUE THREAD

**Issue by robinator8** [melvyn2/MenuPlaythrough#1]
I've been looking around for an app like this for a while and this looks perfect.

I'm trying to get it running but am having some trouble.

I cloned it and ran

```
pip3 install -U pyobjc
pip3 install rumps
pip3 install sounddevice
```

when I run the code I get the following error:

```
Traceback (most recent call last):
  File "./main.py", line 281, in <module>
    app = MenuPlaythroughApp()
  File "./main.py", line 103, in __init__
    sd.set_device_changed_callback(self.full_refresh_devices)
AttributeError: module 'sounddevice' has no attribute 'set_device_changed_callback'
```

**Comment by robinator8** [comment]
I see that you're using a custom fork from here. 

https://github.com/spatialaudio/python-sounddevice
